sudo: required

language: generic

services:
 - docker

before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t heun/docker-react-app -f Dockerfile.dev .

script:
 - docker run -e CI=true heun/docker-react-app npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-react-app"
 env: "Docker-react-app-env"
 bucket_name: "elasticbeanstalk-us-east-1-706657399475"
 bucket_path: "docker-react-app"
 on:
  branch: master